name: Build and Release

on:
  push:
    branches: [ main ]
    tags: [ 'v*' ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Test and Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-dev portaudio19-dev

      - name: Install uv
        uses: astral-sh/setup-uv@v3
        with:
          version: "latest"

      - name: Run linters
        run: make lint

      - name: Build application
        run: make package

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts
          path: |
            dist/

  release:
    name: Create Release
    if: startsWith(github.ref, 'refs/tags/v')
    needs: test
    runs-on: ubuntu-latest
    permissions:
      contents: write
      actions: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-dev portaudio19-dev

      - name: Install uv
        uses: astral-sh/setup-uv@v3
        with:
          version: "latest"

      - name: Create release package
        run: make package

      - name: Extract version from tag
        id: version
        run: echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_OUTPUT

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          name: VoxVibe v${{ steps.version.outputs.VERSION }}
          draft: false
          prerelease: false
          generate_release_notes: true
          files: |
            dist/voxvibe-*.tar.gz
          body: |
            ## VoxVibe v${{ steps.version.outputs.VERSION }}
            
            ### Installation
            
            #### From Release Package (Recommended)
            1. Download `voxvibe-${{ steps.version.outputs.VERSION }}.tar.gz`
            2. Extract: `tar -xzf voxvibe-${{ steps.version.outputs.VERSION }}.tar.gz`
            3. Run: `cd voxvibe-${{ steps.version.outputs.VERSION }} && ./install.sh`
            
            #### From Python Wheel
            1. Download the `.whl` file
            2. Install: `pipx install voxvibe-${{ steps.version.outputs.VERSION }}-*.whl`
            3. Manually install the GNOME extension from the release package
            
            ### Requirements
            - Python 3.11+
            - GNOME Shell 48+
            - Audio recording capabilities (microphone)
            
            For detailed installation and usage instructions, see the [README](https://github.com/${{ github.repository }}/blob/main/README.md).

  build-on-pr:
    name: Build on PR
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-dev portaudio19-dev

      - name: Install uv
        uses: astral-sh/setup-uv@v3
        with:
          version: "latest"

      - name: Check tools and run tests
        run: |
          make lint
          make package

      - name: Comment PR with build status
        if: github.event.pull_request.head.repo.full_name == github.repository && success()
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '✅ Build completed successfully! Ready for review.'
            })